-- --------------------------------------------------------

--
-- Estrutura da tabela `propostas_veiculos`
--

CREATE TABLE IF NOT EXISTS `propostas_veiculos` (
  `num_proposta` int(11) NOT NULL AUTO_INCREMENT,
  `dataproposta` varchar(50) DEFAULT NULL,
  `horaproposta` varchar(50) DEFAULT NULL,
  `mes_ano` varchar(50) DEFAULT NULL,
  `estabelecimento_proposta` varchar(50) DEFAULT NULL,
  `operador_atendente` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tipo` varchar(50) DEFAULT NULL,
  `tipo_proposta` varchar(50) DEFAULT NULL,
  `nome` varchar(50) DEFAULT NULL,
  `tipo_pessoa` varchar(50) DEFAULT NULL,
  `data_nasc` varchar(50) DEFAULT NULL,
  `cpf` varchar(50) DEFAULT NULL,
  `rg` varchar(50) DEFAULT NULL,
  `orgao` varchar(50) DEFAULT NULL,
  `emissao` varchar(50) DEFAULT NULL,
  `sexo` varchar(50) DEFAULT NULL,
  `estadocivil` varchar(50) DEFAULT NULL,
  `nacionalidade` varchar(50) DEFAULT NULL,
  `quant_dependente` varchar(50) DEFAULT NULL,
  `pai` varchar(50) DEFAULT NULL,
  `mae` varchar(50) DEFAULT NULL,
  `conjuge` varchar(50) DEFAULT NULL,
  `data_nasc_conjuge` varchar(50) DEFAULT NULL,
  `endereco` varchar(50) DEFAULT NULL,
  `numero` varchar(50) DEFAULT NULL,
  `bairro` varchar(50) DEFAULT NULL,
  `complemento` varchar(50) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `cep` varchar(50) DEFAULT NULL,
  `correspondencia` varchar(50) DEFAULT NULL,
  `tipo_residencia` varchar(50) DEFAULT NULL,
  `valor_aluguel` varchar(50) DEFAULT NULL,
  `tempo_residencia` varchar(50) DEFAULT NULL,
  `telefone` varchar(50) DEFAULT NULL,
  `celular` varchar(50) DEFAULT NULL,
  `tipo_telefone` varchar(50) DEFAULT NULL,
  `residencia_anterior` varchar(50) DEFAULT NULL,
  `bairro_anterior` varchar(50) DEFAULT NULL,
  `cidade_anterior` varchar(50) DEFAULT NULL,
  `estado_anterior` varchar(50) DEFAULT NULL,
  `tempo_residencia_anterior` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `empresa` varchar(50) DEFAULT NULL,
  `porte_empresa` varchar(50) DEFAULT NULL,
  `data_admissao` varchar(50) DEFAULT NULL,
  `inicio_atividade` varchar(50) DEFAULT NULL,
  `end_empresa` varchar(50) DEFAULT NULL,
  `numero_empresa` varchar(50) DEFAULT NULL,
  `complemento_empresa` varchar(50) DEFAULT NULL,
  `bairro_empresa` varchar(50) DEFAULT NULL,
  `cep_empresa` varchar(50) DEFAULT NULL,
  `cidade_empresa` varchar(50) DEFAULT NULL,
  `estado_empresa` varchar(50) DEFAULT NULL,
  `telefone_empresa` varchar(50) DEFAULT NULL,
  `cpt` varchar(50) DEFAULT NULL,
  `serie` varchar(50) DEFAULT NULL,
  `cargo` varchar(50) DEFAULT NULL,
  `natureza_operacao` varchar(50) DEFAULT NULL,
  `salario` varchar(50) DEFAULT NULL,
  `atividade_principal` varchar(50) DEFAULT NULL,
  `data_constituicao` varchar(50) DEFAULT NULL,
  `cnpj` varchar(50) DEFAULT NULL,
  `inscr_est` varchar(50) DEFAULT NULL,
  `tel_contador` varchar(50) DEFAULT NULL,
  `atividade_anterior` varchar(50) DEFAULT NULL,
  `data_admissao_anterior` varchar(50) DEFAULT NULL,
  `data_saida` varchar(50) DEFAULT NULL,
  `cargo_anterior` varchar(50) DEFAULT NULL,
  `telefone_empresa_anterior` varchar(50) DEFAULT NULL,
  `outras_rendas` varchar(50) DEFAULT NULL,
  `ref_pessoal` varchar(50) DEFAULT NULL,
  `tel_ref_pessoal` varchar(50) DEFAULT NULL,
  `ref_pessoal2` varchar(50) DEFAULT NULL,
  `tel_ref_pessoal2` varchar(50) DEFAULT NULL,
  `ref_comercial` varchar(50) DEFAULT NULL,
  `tel_ref_comercial` varchar(50) DEFAULT NULL,
  `ref_banco` varchar(50) DEFAULT NULL,
  `ref_agencia` varchar(50) DEFAULT NULL,
  `ref_conta` varchar(50) DEFAULT NULL,
  `ref_tipo_conta` varchar(50) DEFAULT NULL,
  `ref_conta_desde` varchar(50) DEFAULT NULL,
  `cartao_credito` varchar(50) DEFAULT NULL,
  `automovel` varchar(50) DEFAULT NULL,
  `valor_automoveis` varchar(50) DEFAULT NULL,
  `residencia` varchar(50) DEFAULT NULL,
  `valor_residencia` varchar(50) DEFAULT NULL,
  `outras_propriedades` varchar(50) DEFAULT NULL,
  `valor_outras_propriedades` varchar(50) DEFAULT NULL,
  `veiculo` varchar(50) DEFAULT NULL,
  `ano_modelo` varchar(50) DEFAULT NULL,
  `renavam` varchar(50) DEFAULT NULL,
  `num_portas` varchar(50) DEFAULT NULL,
  `combustivel` varchar(50) DEFAULT NULL,
  `placa` varchar(50) DEFAULT NULL,
  `valor_venda` varchar(50) DEFAULT NULL,
  `valor_entrada` varchar(50) DEFAULT NULL,
  `tarifa_cadastro` varchar(50) DEFAULT NULL,
  `valor_financiar` varchar(50) DEFAULT NULL,
  `coeficiente` varchar(50) DEFAULT NULL,
  `codigo_tabela` varchar(50) DEFAULT NULL,
  `num_parcelas` varchar(50) DEFAULT NULL,
  `valor_parcelas` varchar(50) DEFAULT NULL,
  `vencto_1_parcela` varchar(50) DEFAULT NULL,
  `r` varchar(50) DEFAULT NULL,
  `valor_liberado` varchar(50) DEFAULT NULL,
  `pagto_serv_terc` varchar(50) DEFAULT NULL,
  `obs` text,
  `operador` varchar(50) DEFAULT NULL,
  `cel_operador` varchar(50) DEFAULT NULL,
  `email_operador` varchar(50) DEFAULT NULL,
  `estab_pertence` varchar(50) DEFAULT NULL,
  `cidade_estab_pertence` varchar(50) DEFAULT NULL,
  `tel_estab_pertence` varchar(50) DEFAULT NULL,
  `email_estab_pertence` varchar(50) DEFAULT NULL,
  `operador_alterou` varchar(50) DEFAULT NULL,
  `cel_operador_alterou` varchar(50) DEFAULT NULL,
  `email_operador_alterou` varchar(50) DEFAULT NULL,
  `estab_alterou` varchar(50) DEFAULT NULL,
  `cidade_estab_alterou` varchar(50) DEFAULT NULL,
  `tel_estab_alterou` varchar(50) DEFAULT NULL,
  `email_estab_alterou` varchar(50) DEFAULT NULL,
  `dataalteracao` varchar(50) DEFAULT NULL,
  `horaalteracao` varchar(50) DEFAULT NULL,
  `recebido` varchar(50) DEFAULT NULL,
  `comissao_op` varchar(50) DEFAULT NULL,
  `meses` varchar(50) DEFAULT NULL,
  `trinta` varchar(50) DEFAULT NULL,
  `quarenta_cinco` varchar(50) DEFAULT NULL,
  `meses_residencia` varchar(50) DEFAULT NULL,
  `ddd_tel` varchar(50) DEFAULT NULL,
  `ddd_cel` varchar(50) DEFAULT NULL,
  `ddd_tel_empresa` varchar(50) DEFAULT NULL,
  `ddd_tel_contador` varchar(50) DEFAULT NULL,
  `ddd_tel_empresa_anterior` varchar(50) DEFAULT NULL,
  `ddd_ref_pessoal` varchar(50) DEFAULT NULL,
  `ddd_ref_pessoal2` varchar(50) DEFAULT NULL,
  `ddd_ref_comercial` varchar(50) DEFAULT NULL,
  `digito_agencia` varchar(50) DEFAULT NULL,
  `digito_conta` varchar(50) DEFAULT NULL,
  `ano_ref_conta` varchar(50) DEFAULT NULL,
  `modelo` varchar(50) DEFAULT NULL,
  `estado_emissao` varchar(50) DEFAULT NULL,
  `mista` varchar(50) DEFAULT NULL,
  `parecer_credito` text,
  `bem` varchar(50) DEFAULT NULL,
  `chassi` varchar(50) DEFAULT NULL,
  `incluir_avalista` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`num_proposta`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=548 ;

--
-- Extraindo dados da tabela `propostas_veiculos`
--

INSERT INTO `propostas_veiculos` (`num_proposta`, `dataproposta`, `horaproposta`, `mes_ano`, `estabelecimento_proposta`, `operador_atendente`, `status`, `tipo`, `tipo_proposta`, `nome`, `tipo_pessoa`, `data_nasc`, `cpf`, `rg`, `orgao`, `emissao`, `sexo`, `estadocivil`, `nacionalidade`, `quant_dependente`, `pai`, `mae`, `conjuge`, `data_nasc_conjuge`, `endereco`, `numero`, `bairro`, `complemento`, `cidade`, `estado`, `cep`, `correspondencia`, `tipo_residencia`, `valor_aluguel`, `tempo_residencia`, `telefone`, `celular`, `tipo_telefone`, `residencia_anterior`, `bairro_anterior`, `cidade_anterior`, `estado_anterior`, `tempo_residencia_anterior`, `email`, `empresa`, `porte_empresa`, `data_admissao`, `inicio_atividade`, `end_empresa`, `numero_empresa`, `complemento_empresa`, `bairro_empresa`, `cep_empresa`, `cidade_empresa`, `estado_empresa`, `telefone_empresa`, `cpt`, `serie`, `cargo`, `natureza_operacao`, `salario`, `atividade_principal`, `data_constituicao`, `cnpj`, `inscr_est`, `tel_contador`, `atividade_anterior`, `data_admissao_anterior`, `data_saida`, `cargo_anterior`, `telefone_empresa_anterior`, `outras_rendas`, `ref_pessoal`, `tel_ref_pessoal`, `ref_pessoal2`, `tel_ref_pessoal2`, `ref_comercial`, `tel_ref_comercial`, `ref_banco`, `ref_agencia`, `ref_conta`, `ref_tipo_conta`, `ref_conta_desde`, `cartao_credito`, `automovel`, `valor_automoveis`, `residencia`, `valor_residencia`, `outras_propriedades`, `valor_outras_propriedades`, `veiculo`, `ano_modelo`, `renavam`, `num_portas`, `combustivel`, `placa`, `valor_venda`, `valor_entrada`, `tarifa_cadastro`, `valor_financiar`, `coeficiente`, `codigo_tabela`, `num_parcelas`, `valor_parcelas`, `vencto_1_parcela`, `r`, `valor_liberado`, `pagto_serv_terc`, `obs`, `operador`, `cel_operador`, `email_operador`, `estab_pertence`, `cidade_estab_pertence`, `tel_estab_pertence`, `email_estab_pertence`, `operador_alterou`, `cel_operador_alterou`, `email_operador_alterou`, `estab_alterou`, `cidade_estab_alterou`, `tel_estab_alterou`, `email_estab_alterou`, `dataalteracao`, `horaalteracao`, `recebido`, `comissao_op`, `meses`, `trinta`, `quarenta_cinco`, `meses_residencia`, `ddd_tel`, `ddd_cel`, `ddd_tel_empresa`, `ddd_tel_contador`, `ddd_tel_empresa_anterior`, `ddd_ref_pessoal`, `ddd_ref_pessoal2`, `ddd_ref_comercial`, `digito_agencia`, `digito_conta`, `ano_ref_conta`, `modelo`, `estado_emissao`, `mista`, `parecer_credito`, `bem`, `chassi`, `incluir_avalista`) VALUES
(545, '09/06/2011', '07:23:44', '06-2011', 'SHOP CAR', 'MARCELO FARIA UEHARA', 'Proposta_Paga', 'Proponente', 'CDC', 'cliente teste', '', '15-10-2009', '07116379622', '654654654654', 'ssp', '16-10-2009', 'Masculino', 'Casado', 'Brasileira', '2', 'teste', 'teste', 'çlljlkj', 'çlkj', 'çlkj', 'lkçj', 'çlkj', 'çlkj', 'çlkj', 'Acre', 'çlkj', 'Residencial', 'Própria', '0.00', '5', '946565465', '65166514', 'Próprio', 'çkjk', 'jl', 'çkjlçj', 'Acre', 'lçj', 'kjkljlçkjlçjçjlçkjl@ljalkfjasldjlçdjf.com.br', 'klçlkjçjç', 'Grande', '4', 'mç.kl', 'jlçjklkj', 'çlkjçljk', 'çlkj', 'çlj', 'çlkj', 'lçkj', 'Acre', 'çljk', '', '', 'l', 'Empresa Privada - CLT', '10000.00', 'kjhlkhlk', '', 'ljhlkh', '', 'lkjh', 'jhljk', 'lkjh', 'lkjh', 'lkjh', 'lkjh', 'lkjlkjh', 'lkjh', 'lkjh', 'lkjh', 'kljh', 'kljh', 'lkj', 'lkjh', 'lkjh', 'lkjh', 'Comum', 'jk', 'Visa', 'Tem um', '15000.00', 'Residência Própria', '500000.00', 'Fazenda(s)', '1500000.00', 'airbus', '2012', 'jçljlçkjklç', '2', 'Gasolina', '', '25000.00', '6000.00', '855.00', '19855.00', '0.03432', '654654', '60', '681.42', '', '2', '0.00', '456.00', 'teste', 'MARCELO FARIA UEHARA', '16 9163-2434', 'muehara@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', 'EVERTON POSSETTI', '(16) 9157-7648', 'epossetti@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', '16/06/2011', '12:56:32', NULL, NULL, '5', '', '45 DD', '8', '16', '16', 'çl', 'kj', 'lk', 'kl', 'lk', 'lk', 'lk', 'lk', 'lçk', '2012', 'SP', 'Não', 'teste', 'Semi-Novo', 'çjçlkjlçjlçjlç', 'Não'),
(544, '08/06/2011', '15:22:34', '06-2011', 'SHOP CAR', 'MARCELO FARIA UEHARA', 'Em Andamento', 'Proponente', 'CDC', 'VALDINEIA XAVIER LIMA', '', '04-07-1980', '07116379622', 'MG6818', 'SSP', '', 'Feminino', 'Solteiro', 'Brasileira', '0', 'WALTER CANDIDO LIMA', 'TEREZINHA XAVIER LIMA', '', '', 'RUA CORONEL LOURENÇO BELO', '72', 'CENTRO', '', 'CAPITOLIO', 'Minas_Gerais', '37930-000', 'Residencial', 'Própria', '', '5', '3373-1142', '9812-7221', 'Próprio', '', '', '', '', '', '', 'ROBERTA ESPINHA CORREIA', 'Pequeno', '', '', 'RUA GALERAS', '350', '', 'ESCARPA DO LAGO', '37930-000', 'CAPITOLIO', 'Minas_Gerais', '080020070', '', '', 'GOVERNANTA', 'Empresa Privada - CLT', '3500.00', '', '', '', '', '', '', '', '', '', '', '', 'APARECIDA A SILVA', '3373-1339', 'JOEL L COSTA', '3373-1985', '', '', '', '', '', 'Não Tem', '', 'Não tem', 'Não tem', '', 'Não tem', '', 'Não tem', '', 'ASTRA HACTH', '2006', '', '4', 'Gasolina', '', '32400.00', '5000.00', '855.00', '28255.00', '0.02821', 'LBOF20', '60', '797.07', '', '2', '0.00', '657.60', 'TESTE', 'MARCELO FARIA UEHARA', '16 9163-2434', 'muehara@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '06', '30 DD', '', '2', '37', '37', '31', '', '', '37', '37', '', '', '', '', '2007', 'MG', 'Não', NULL, 'Semi-Novo', '', 'Não'),
(546, '01/07/2011', '17:01:03', '07-2011', 'Selecione a loja', '', 'Em Andamento', 'Proponente', 'CDC', 'leandro carvalho de castro', '', '', '18649261809', '258017260', 'ssp', '20051990', 'Masculino', 'Solteiro', 'Brasileira', '01', 'nilo cairo de castro', 'LEDA MARIA CARVALHO DE CASTRO', '', '31/12/1977', 'RUA SALIM FERES ', '353', 'centro', 'CASA', 'pedregulho', 'Sao_Paulo', '144470000', 'Residencial', 'Própria', '', '10', '31711144', '91614102', 'Próprio', '', '', '', '', '', '', 'investti', 'Grande', '1,5', '', '', '', '', '', '', '', '', '', '', '', '', 'Empresa Privada - CLT', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Não Tem', '', 'Não tem', 'Não tem', '', 'Não tem', '', 'Não tem', '', 'Digitar igual no CRV', '', '', '2', 'Gasolina', '', '', '', '', '0.00', '', '', '', '0.00', '', '', '0.00', '0.00', '', 'LEANDRO CARVALHO DE CASTRO', '016 9161-4102', 'lccastro@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', '0', '16', '16', '', '', '', '', '', '', '', '', '', '', 'SP', '', NULL, '', '', 'Não'),
(547, '15/07/2011', '16:03:55', '07-2011', 'SHOP CAR', 'MARCELO FARIA UEHARA', 'Proposta_Paga', 'Proponente', 'CDC', 'ze das cove', '', 'zsdfgsdfg', '123456789', 'sdfgsdfg', 'sdfghsdfg', 'sdfg', 'Masculino', 'Casado', 'Brasileira', '2', 'sdfgsdfgsdfg', 'sdfgsdfgdsfg', 'sdfgs', 'sdfgs', 'dfgsdfg', 'dfgsdf', 'sdfgsdfg', 'sdfg', 'sdfgsdfg', 'Roraima', 'gsdfg', 'Residencial', 'Com', 'sdfgsdfg', 'sdfgsdf', 'sdfgsdf', 'sdfgsdfg', 'Próprio', 'dfsgsdf', 'sdfgsdf', 'gsdfg', 'Rondonia', 'sdfgsdfg', 'sdfgsdfg', 'sdfgsdfg', 'Grande', 'sdg', 'sdfgsdfg', 'sdfgsdfg', 'sdfgsd', 'sdfgsdfg', 'sdfgsdfg', 'xcvbxcvbxcvb', 'sdgsdfgdf', 'Sao_Paulo', 'xcvbxcvbx', '', '', 'gsdfgsdfg', 'Empresa Privada - CLT', 'sdfgsdf', 'xcvbxcvbxc', '', 'sdfgsdfg', '', 'vbxcvb', 'xcvbxcvb', 'xcvbxcvb', 'xcvbxcvbb', 'ncvncvcgh', 'bxcvbxcvb', 'xcvbxcvb', 'xcvbxcvbcvb', 'xcvbxcvb', 'xcbxcvb', 'xcvbxcvb', 'xcbxcvbcxvb', 'xbxcbxcvb', 'xcbxcvbxcv', 'xcvbxcbxcv', 'xcbxcvb', 'Não Tem', 'xc', 'Não tem', 'Não tem', 'sdfgsdfg', 'Não tem', 'sdfgsdfgsdf', 'Não tem', 'gdsfgsdfgdf', 'Digitar igual no CRV', 'sdfg', 'sdfgsdfg', '2', 'Gasolina', 'sdfgsdfg', '50000.00', '5000.00', '855.00', '45855.00', '0.2900', '56461', '60', '13297.95', '', '4', '0.00', '2160.00', 'teste', 'MARCELO FARIA UEHARA', '16 9163-2434', 'muehara@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', 'MARCELO FARIA UEHARA', '16 9163-2434', 'muehara@investti.com.br', 'INVESTTI - SERVIÇOS FINANCEIROS', 'FRANCA', '(16) 3406-7148', 'contato@investti.com.br', '15/07/2011', '16:41:42', NULL, NULL, 'sdfgsdfg', '', '', 'sdfgds', 'gs', 'sd', 'xc', 'vb', 'zd', 'xc', 'xc', 'xc', 'xc', 'xc', 'xcvb', 'sdfg', 'AC', 'Não', '', 'Usado', 'sdgsdfgsdfg', 'Não');

-- --------------------------------------------------------

--
-- Estrutura da tabela `propostas_veiculos_avalistas`
--

CREATE TABLE IF NOT EXISTS `propostas_veiculos_avalistas` (
  `num_proposta` int(11) NOT NULL AUTO_INCREMENT,
  `dataproposta` varchar(50) DEFAULT NULL,
  `horaproposta` varchar(50) DEFAULT NULL,
  `mes_ano` varchar(50) DEFAULT NULL,
  `estabelecimento_proposta` varchar(50) DEFAULT NULL,
  `operador_atendente` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tipo` varchar(50) DEFAULT NULL,
  `tipo_proposta` varchar(50) DEFAULT NULL,
  `nome` varchar(50) DEFAULT NULL,
  `tipo_pessoa` varchar(50) DEFAULT NULL,
  `data_nasc` varchar(50) DEFAULT NULL,
  `cpf` varchar(50) DEFAULT NULL,
  `rg` varchar(50) DEFAULT NULL,
  `orgao` varchar(50) DEFAULT NULL,
  `emissao` varchar(50) DEFAULT NULL,
  `sexo` varchar(50) DEFAULT NULL,
  `estadocivil` varchar(50) DEFAULT NULL,
  `nacionalidade` varchar(50) DEFAULT NULL,
  `quant_dependente` varchar(50) DEFAULT NULL,
  `pai` varchar(50) DEFAULT NULL,
  `mae` varchar(50) DEFAULT NULL,
  `conjuge` varchar(50) DEFAULT NULL,
  `data_nasc_conjuge` varchar(50) DEFAULT NULL,
  `endereco` varchar(50) DEFAULT NULL,
  `numero` varchar(50) DEFAULT NULL,
  `bairro` varchar(50) DEFAULT NULL,
  `complemento` varchar(50) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `cep` varchar(50) DEFAULT NULL,
  `correspondencia` varchar(50) DEFAULT NULL,
  `tipo_residencia` varchar(50) DEFAULT NULL,
  `valor_aluguel` varchar(50) DEFAULT NULL,
  `tempo_residencia` varchar(50) DEFAULT NULL,
  `telefone` varchar(50) DEFAULT NULL,
  `celular` varchar(50) DEFAULT NULL,
  `tipo_telefone` varchar(50) DEFAULT NULL,
  `residencia_anterior` varchar(50) DEFAULT NULL,
  `bairro_anterior` varchar(50) DEFAULT NULL,
  `cidade_anterior` varchar(50) DEFAULT NULL,
  `estado_anterior` varchar(50) DEFAULT NULL,
  `tempo_residencia_anterior` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `empresa` varchar(50) DEFAULT NULL,
  `porte_empresa` varchar(50) DEFAULT NULL,
  `data_admissao` varchar(50) DEFAULT NULL,
  `inicio_atividade` varchar(50) DEFAULT NULL,
  `end_empresa` varchar(50) DEFAULT NULL,
  `numero_empresa` varchar(50) DEFAULT NULL,
  `complemento_empresa` varchar(50) DEFAULT NULL,
  `bairro_empresa` varchar(50) DEFAULT NULL,
  `cep_empresa` varchar(50) DEFAULT NULL,
  `cidade_empresa` varchar(50) DEFAULT NULL,
  `estado_empresa` varchar(50) DEFAULT NULL,
  `telefone_empresa` varchar(50) DEFAULT NULL,
  `cpt` varchar(50) DEFAULT NULL,
  `serie` varchar(50) DEFAULT NULL,
  `cargo` varchar(50) DEFAULT NULL,
  `natureza_operacao` varchar(50) DEFAULT NULL,
  `salario` varchar(50) DEFAULT NULL,
  `atividade_principal` varchar(50) DEFAULT NULL,
  `data_constituicao` varchar(50) DEFAULT NULL,
  `cnpj` varchar(50) DEFAULT NULL,
  `inscr_est` varchar(50) DEFAULT NULL,
  `tel_contador` varchar(50) DEFAULT NULL,
  `atividade_anterior` varchar(50) DEFAULT NULL,
  `data_admissao_anterior` varchar(50) DEFAULT NULL,
  `data_saida` varchar(50) DEFAULT NULL,
  `cargo_anterior` varchar(50) DEFAULT NULL,
  `telefone_empresa_anterior` varchar(50) DEFAULT NULL,
  `outras_rendas` varchar(50) DEFAULT NULL,
  `ref_pessoal` varchar(50) DEFAULT NULL,
  `tel_ref_pessoal` varchar(50) DEFAULT NULL,
  `ref_pessoal2` varchar(50) DEFAULT NULL,
  `tel_ref_pessoal2` varchar(50) DEFAULT NULL,
  `ref_comercial` varchar(50) DEFAULT NULL,
  `tel_ref_comercial` varchar(50) DEFAULT NULL,
  `ref_banco` varchar(50) DEFAULT NULL,
  `ref_agencia` varchar(50) DEFAULT NULL,
  `ref_conta` varchar(50) DEFAULT NULL,
  `ref_tipo_conta` varchar(50) DEFAULT NULL,
  `ref_conta_desde` varchar(50) DEFAULT NULL,
  `cartao_credito` varchar(50) DEFAULT NULL,
  `automovel` varchar(50) DEFAULT NULL,
  `valor_automoveis` varchar(50) DEFAULT NULL,
  `residencia` varchar(50) DEFAULT NULL,
  `valor_residencia` varchar(50) DEFAULT NULL,
  `outras_propriedades` varchar(50) DEFAULT NULL,
  `valor_outras_propriedades` varchar(50) DEFAULT NULL,
  `veiculo` varchar(50) DEFAULT NULL,
  `ano_modelo` varchar(50) DEFAULT NULL,
  `renavam` varchar(50) DEFAULT NULL,
  `num_portas` varchar(50) DEFAULT NULL,
  `combustivel` varchar(50) DEFAULT NULL,
  `placa` varchar(50) DEFAULT NULL,
  `valor_venda` varchar(50) DEFAULT NULL,
  `valor_entrada` varchar(50) DEFAULT NULL,
  `tarifa_cadastro` varchar(50) DEFAULT NULL,
  `valor_financiar` varchar(50) DEFAULT NULL,
  `coeficiente` varchar(50) DEFAULT NULL,
  `codigo_tabela` varchar(50) DEFAULT NULL,
  `num_parcelas` varchar(50) DEFAULT NULL,
  `valor_parcelas` varchar(50) DEFAULT NULL,
  `vencto_1_parcela` varchar(50) DEFAULT NULL,
  `r` varchar(50) DEFAULT NULL,
  `valor_liberado` varchar(50) DEFAULT NULL,
  `pagto_serv_terc` varchar(50) DEFAULT NULL,
  `obs` text,
  `operador` varchar(50) DEFAULT NULL,
  `cel_operador` varchar(50) DEFAULT NULL,
  `email_operador` varchar(50) DEFAULT NULL,
  `estab_pertence` varchar(50) DEFAULT NULL,
  `cidade_estab_pertence` varchar(50) DEFAULT NULL,
  `tel_estab_pertence` varchar(50) DEFAULT NULL,
  `email_estab_pertence` varchar(50) DEFAULT NULL,
  `operador_alterou` varchar(50) DEFAULT NULL,
  `cel_operador_alterou` varchar(50) DEFAULT NULL,
  `email_operador_alterou` varchar(50) DEFAULT NULL,
  `estab_alterou` varchar(50) DEFAULT NULL,
  `cidade_estab_alterou` varchar(50) DEFAULT NULL,
  `tel_estab_alterou` varchar(50) DEFAULT NULL,
  `email_estab_alterou` varchar(50) DEFAULT NULL,
  `dataalteracao` varchar(50) DEFAULT NULL,
  `horaalteracao` varchar(50) DEFAULT NULL,
  `recebido` varchar(50) DEFAULT NULL,
  `comissao_op` varchar(50) DEFAULT NULL,
  `meses` varchar(50) DEFAULT NULL,
  `trinta` varchar(50) DEFAULT NULL,
  `quarenta_cinco` varchar(50) DEFAULT NULL,
  `meses_residencia` varchar(50) DEFAULT NULL,
  `ddd_tel` varchar(50) DEFAULT NULL,
  `ddd_cel` varchar(50) DEFAULT NULL,
  `ddd_tel_empresa` varchar(50) DEFAULT NULL,
  `ddd_tel_contador` varchar(50) DEFAULT NULL,
  `ddd_tel_empresa_anterior` varchar(50) DEFAULT NULL,
  `ddd_ref_pessoal` varchar(50) DEFAULT NULL,
  `ddd_ref_pessoal2` varchar(50) DEFAULT NULL,
  `ddd_ref_comercial` varchar(50) DEFAULT NULL,
  `digito_agencia` varchar(50) DEFAULT NULL,
  `digito_conta` varchar(50) DEFAULT NULL,
  `ano_ref_conta` varchar(50) DEFAULT NULL,
  `modelo` varchar(50) DEFAULT NULL,
  `estado_emissao` varchar(50) DEFAULT NULL,
  `mista` varchar(50) DEFAULT NULL,
  `parecer_credito` text,
  `bem` varchar(50) DEFAULT NULL,
  `chassi` varchar(50) DEFAULT NULL,
  `incluir_avalista` varchar(50) DEFAULT NULL,
  `num_proposta_proponente` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`num_proposta`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------
